### PR TITLE
Issue #19 fix verify_deploy()

### LINKED ISSUE #19: Update verify_deploy in CI
## Description

While [updating our CI configuration](https://github.com/IBM/Scalable-Cassandra-deployment-on-Kubernetes/pull/18), I found that our `verify_deploy` function is not verifying the service is actually up.

## Requested steps

Unfortunately, I have not had a chance to look closely at this yet, so we will need to come back to it. For now, the service is being deployed, and checked via kubectl.

### PR DESCRIPTION
**Pull request by markstur**
Fixes #19 
verify_deploy() wasn't failing because conditional logic needs parens.

### CODE REVIEW

**Comment by markstur** [comment]
@loafyloaf @mlangbehn There was a logic problem there. Pretty confident I was able to fix test that specific scripting, but not in the overall context of the code pattern.

**Comment by AnthonyAmanse** [comment]
@markstur shellcheck lint is failing
https://travis-ci.org/IBM/Scalable-Cassandra-deployment-on-Kubernetes/builds/560081036
```
if [ ! -z "$CASSANDRA_SEEDS" ]; then
     ^-- SC2236: Use -n instead of ! -z.
```

**Comment by markstur** [comment]
@AnthonyAmanse thanks for the heads-up. Odd that it passed on my private repo and the error is in an untouched file, but it is a straightforward fix so... done.

**Review by AnthonyAmanse — APPROVED** [review]

**Review by loafyloaf — COMMENTED** [review]
word

**Pull request merged**
